### ISSUE TITLE
"error":"invalid_client"

### ISSUE THREAD

**Issue by M8874** [tthn0/Spotify-Readme#14]
Hello, I have an `"error":"invalid_client"` issue.
I did as it was written, created a string in the format
And encoded it in Base64
And sent a `curl` request
```bash
curl \
-X POST \
-H "Content-Type: application/x-www-form-urlencoded" \
-H "Authorization: Basic {YzM...REDACTED...MzM=}" \
-d "grant_type=authorization_code&redirect_uri=[http://localhost/callback/&code={AQDzjaRztvKyjHB5XuaMGgZO2XyBCygxqVs2lSFnBsMUyyTo-K2W_mV8uf4qKhmNfaSdtwZ5s3MkFNXvp3KpgueowjB6VCAiw2fkEC7QJdBAJDrOnrwUQBzl3kODDUox8fX8fnsB-P6e5-9JKjL-SfPp7GzQxhHUNqilOasGO8TwBaPsv36vFxeswv2Tm6dft4LI0MMTYLmQ7c_stIF6QfSZElbpy2nJpVI5gQL8}](http://localhost/callback/&code=%7BAQDzjaRztvKyjHB5XuaMGgZO2XyBCygxqVs2lSFnBsMUyyTo-K2W_mV8uf4qKhmNfaSdtwZ5s3MkFNXvp3KpgueowjB6VCAiw2fkEC7QJdBAJDrOnrwUQBzl3kODDUox8fX8fnsB-P6e5-9JKjL-SfPp7GzQxhHUNqilOasGO8TwBaPsv36vFxeswv2Tm6dft4LI0MMTYLmQ7c_stIF6QfSZElbpy2nJpVI5gQL8%7D)" \
https://accounts.spotify.com/api/token
```
and received the error response `"error":"invalid_client"`

**Comment by tthn0** [comment]
Hello @M8874,

Please do not share your **Client Secret** to the public, even in its Base64 encoded form. I just edited your response to remove it. The issue here is that you wrapped curly braces around your Base64 encoded string. Please remove those before making your `curl` request, and it should work fine.

**Correct**:

```
"Authorization: Basic qJiLwViEYlyviJcMfscrxSuyBFEOkytAsCoonBqzNORhKEtTmEfBTuXOZOZcApyiwXlvvQvSIJfCndZiH="
```

**Incorrect**:

```
"Authorization: Basic {qJiLwViEYlyviJcMfscrxSuyBFEOkytAsCoonBqzNORhKEtTmEfBTuXOZOZcApyiwXlvvQvSIJfCndZiH =}"
```

**Comment by M8874** [comment]
Thank you for the response. In the example there, I changed 9 characters, don't worry about security.

**Comment by M8874** [comment]
Thank you very much @tthn0. I fixed the code, but now I have a new error. I don't know why it occurred, but I've already checked everything. As far as I understand, the error is with the indicator  

{"error":"invalid_client","error_description":"Invalid client"}



curl \
  -X POST \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -H "Authorization: Basic e2MzMmVlMjgxZDc1gyg5NDVlODhiZGNkYjEyMjhhhTE0NzJjjNDIzN2Ez7MGY0ODc1OGJiMzN9" \
  -d "grant_type=authorization_code&redirect_uri=http://localhost/callback/&code=AQA33N-LHY0Y6eW3CJ702_5DtncKsSKXWv7VffgfggertgL3Ws3sgaDhu9uomJhqZxjXVMV9lQlZGhnAORjStOdWuPxhvvoe-_GJr6C9cGocpcCs2SI0u3Au4x3MCmWUlmW4O6oh_b_MUjTu_3ls7Zi58neoGj587xarCpDfXqddeWAX6ydDflKnRIVYaP_RZ-zZte_tExgHUM" \
  https://accounts.spotify.com/api/token

**Comment by tthn0** [comment]
For your `-H` flag that represents authorization, are you sure you encoded your `{CLIENT_ID}:{CLIENT_SECRET}` correctly? Usually the encoded string should end with an equal sign.

**Comment by M8874** [comment]
Hello @tthn0, thanks for your help. I seem to be useless; I can't even complete such a simple task. 😉

**Comment by M8874** [comment]
I apologize for such a request; I understand that your time is valuable, and I may be bothering you unnecessarily. Could you please write to me on Telegram at @KapTbl_geHbru?

I just want to understand what I'm doing wrong. I want to add a widget to my web portfolio. Currently, there is a widget that is not mine at https://magical-lokum-134348.netlify.app/.

**Comment by tthn0** [comment]
@M8874 I do not use Telegram unfortunately. Are you on Discord? You may add me there; my username is `tthn`.

**Comment by SVENTRIPIKAL** [comment]
@M8874 hello, I just had the same issue but it happened to be that the {CALLBACK_CODE} that is embedded in the URL when you apply this step `https://accounts.spotify.com/authorize?client_id={CLIENT_ID}&response_type=code&scope=user-read-currently-playing,user-read-recently-played&redirect_uri=http://localhost/callback/` actually expires & returning to that step before running the terminal script helped since it gave me a different code to add to the -d redirect URI. not sure why it did that but after redoing that step the script returns the JSON object with the REFRESH_TOKEN you need. hope this helps.

**Comment by M8874** [comment]
@SVENTRIPIKAL Hello, thanks for your help. I received the REFRESH_TOKEN, but I still can't get anything to work.                                   https://spotify-readme-ten-omega.vercel.app/

**Comment by M8874** [comment]
Who can spend their time and expand this widget, while at the same time showing what I'm doing wrong, will be appreciated.

**Comment by SVENTRIPIKAL** [comment]
@M8874 once you deploy your project on **VERCEL**, you use your project's domain URL, `https://spotify-readme-ten-omega.vercel.app/`, to reference it in your **GITHUB** profile homepage `README.md` like this:

```
<a href="https://github.com/tthn0/Spotify-Readme">
  <img src="https://spotify-readme-ten-omega.vercel.app/api" alt="Current Spotify Song">
</a>
```

and that's pretty much it. if you still have problems send me or anyone else who's helping you a separate message because these errors are not related to project bugs, rather personal errors.
so please mark this issue as closed or resolved.

hope these steps were able to resolve your issue.

**Comment by M8874** [comment]
@SVENTRIPIKAL Thank you for your patience. I'm not sure what I did wrong after deploying the project on Vercel. I'm getting a 404 error.

404: NOT_FOUND
Code: NOT_FOUND
ID: arn1::sh6t6-1696008055784-865b7964986e

**Comment by SVENTRIPIKAL** [comment]
@M8874 add me on Discord, `sventripikal`, and i will help you through there. but mark this issue as closed please.
